# use python image
FROM python:3.9.1-slim

# create dir for sharing sql file
RUN mkdir /sql

# create dir for holding test config json files
RUN mkdir /data

# copy python files
COPY db_setup.py db_setup.py
COPY test/db_setup_test.py db_setup_test.py
COPY test/data /data

# run db setup
CMD ["python", "db_setup_test.py"]
