# use python image
FROM python:3.9.1-slim

# set workdir
WORKDIR /home

# create dir for holding test config json files
RUN mkdir /data

# copy python files
COPY main.py /home/main.py
COPY http_const.py /home/http_const.py
COPY entity_utils.py /home/entity_utils.py
COPY requirements.txt /home/requirements.txt

# install python packages
RUN pip install -r /home/requirements.txt

# run db setup
CMD ["python", "/home/backend_test.py"]
