# use python image
FROM python:3.9.1

# set workdir
WORKDIR /home

# create dir for holding test config json files
RUN mkdir /data

# create dir for holding description file
RUN mkdir /common

# copy python files
COPY main.py /home/main.py
COPY db_helper.py /home/db_helper.py
COPY requirements.txt /home/requirements.txt

# install python packages
RUN pip install -r /home/requirements.txt
RUN pip install requests

# run tests
CMD ["python", "/home/backend_test.py"]
