version: "3"

volumes:
  sql:
  common:
    driver: local
    driver_opts:
      type: overlay2
      device: ./common
      o: bind

services:
  db-init:
    build:
      context: ./init/db
      dockerfile: Dockerfile
    volumes:
      - ./${CONFIG_FILE}:/home/${CONFIG_FILE}
      - ./init/${CONFIG_HELPER_PYTHON_FILE}:/home/${CONFIG_HELPER_PYTHON_FILE}
      - sql:/sql
    environment:
      CONFIG_FILE: ${CONFIG_FILE}
      CONFIG_HELPER_PYTHON_FILE: ${CONFIG_HELPER_PYTHON_FILE}
      DB_INIT_SQL_FILE: ${DB_INIT_SQL_FILE}

  config-init:
    build:
      context: ./init/config
      dockerfile: Dockerfile
    volumes:
      - ./${CONFIG_FILE}:/home/${CONFIG_FILE}
      - ./init/${CONFIG_HELPER_PYTHON_FILE}:/home/${CONFIG_HELPER_PYTHON_FILE}
      - common:/common
    environment:
      CONFIG_FILE: ${CONFIG_FILE}
      CONFIG_HELPER_PYTHON_FILE: ${CONFIG_HELPER_PYTHON_FILE}
      DESCRIPTION_FILE: ${DESCRIPTION_FILE}

  # db:
  #   image: postgres:13.1
  #   restart: always
  #   depends_on:
  #     - db-init
  #   volumes:
  #     - sql:/docker-entrypoint-initdb.d
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - "5432:${POSTGRES_PORT}"
    #command: /bin/sh -c "while [ ! -f /docker-entrypoint-initdb.d/${DB_INIT_FILE} ]; do echo 'waiting for db init script...'; sleep 1; done;"
    #command: /bin/sh -c "while [ ! -f /docker-entrypoint-initdb.d/${DB_INIT_FILE} ]; do echo 'waiting for db init script...'; sleep 1; done;" && postgres
    #command: sudo -u postgres postgres
    #command: "/bin/sh -c echo 'waiting for db init script...'; sleep 1; && postgres"
    #command: /bin/sh -c "echo 'hello world'"

  backend:
    build:
      context: ./backend-server-flask
      dockerfile: Dockerfile
    depends_on:
      - config-init
      - db-init
    volumes:
      - ./init/${CONFIG_HELPER_PYTHON_FILE}:/home/${CONFIG_HELPER_PYTHON_FILE}
      - common:/common
    environment:
      CONFIG_HELPER_PYTHON_FILE: ${CONFIG_HELPER_PYTHON_FILE}
      DESCRIPTION_FILE: ${DESCRIPTION_FILE}
    ports:
      - "5000:${API_PORT}"

  # frontend:
  #   build: './frontend-server-angular'
  #   depends_on:
  #     - backend
  #   ports:
  #     - "4200:${WEB_UI_PORT}"
