version: "3"

services:
  init-test:
    build:
      context: ./init
      dockerfile: test/Dockerfile-test

  db-init-test:
    build:
      context: ./init/db
      dockerfile: test/Dockerfile-test
    volumes:
      - ./init/${CONFIG_HELPER_PYTHON_FILE}:/home/${CONFIG_HELPER_PYTHON_FILE}
      - ./init/test/data:/data
    depends_on:
      - db-init

  config-init-test:
    build:
      context: ./init/config
      dockerfile: test/Dockerfile-test
    volumes:
      - ./init/${CONFIG_HELPER_PYTHON_FILE}:/home/${CONFIG_HELPER_PYTHON_FILE}
      - ./init/test/data:/data
    depends_on:
      - config-init


  #
  # backend:
  #   build: './backend-server-flask'
  #   depends_on:
  #     - "db"
  #   ports:
  #     - "5000:${API_PORT}"
  #
  # frontend:
  #   build: './frontend-server-angular'
  #   depends_on:
  #     - "backend"
  #   ports:
  #     - "4200:${USER_PORT}"
