version: "3"

services:
  init-test:
    build:
      context: ./init
      dockerfile: Dockerfile-test
    volumes:
      - ./utils/${CONFIG_UTILS_PY_FILE}:/home/${CONFIG_UTILS_PY_FILE}
      - ./test/data:/data
      - ./test/config_helper_test.py:/home/config_helper_test.py

  db-init-test:
    build:
      context: ./init/db
      dockerfile: Dockerfile-test
    volumes:
      - ./utils/${CONFIG_UTILS_PY_FILE}:/home/${CONFIG_UTILS_PY_FILE}
      - ./utils/${DB_UTILS_PY_FILE}:/home/${DB_UTILS_PY_FILE}
      - ./test/data:/data
      - ./test/db_setup_test.py:/home/db_setup_test.py

  config-init-test:
    build:
      context: ./init/config
      dockerfile: Dockerfile-test
    volumes:
      - ./utils/${CONFIG_UTILS_PY_FILE}:/home/${CONFIG_UTILS_PY_FILE}
      - ./test/data:/data
      - ./test/description_gen_test.py:/home/description_gen_test.py

  backend-test:
    build:
      context: ./backend-server-flask
      dockerfile: Dockerfile-test
    volumes:
      - ./utils/${CONFIG_UTILS_PY_FILE}:/home/${CONFIG_UTILS_PY_FILE}
      - ./utils/${ENTITY_UTILS_PY_FILE}:/home/${ENTITY_UTILS_PY_FILE}
      - ./utils/${HTTP_UTILS_PY_FILE}:/home/${HTTP_UTILS_PY_FILE}
      - ./utils/${DB_UTILS_PY_FILE}:/home/${DB_UTILS_PY_FILE}
      - ./init/config/description_gen.py:/home/description_gen.py
      - ./test/data:/data
      - ./test/backend_test.py:/home/backend_test.py
