version: "3"
volumes:
  sql:

services:
  db-init:
    build: ./db-setup
    volumes:
      - ./${CONFIG_FILE}:/home/${CONFIG_FILE}
      - sql:/sql

  sql-server:
    image: postgres:13.1
    restart: always
    volumes:
      - sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  # flask-server:
  #   build: './backend'
  #   ports:
  #     - "5000:${API_PORT}"
  # angular-server:
  #   build: './frontend'
  #   ports:
  #     - "4200:${USER_PORT}"
