# use python image
FROM python:3.9.1-slim

# set workdir
WORKDIR /home

# create dir for holding test config json files
RUN mkdir /data

# copy python files
COPY description_gen.py /home/description_gen.py

# run tests
CMD ["python", "/home/description_gen_test.py"]
