# use python image
FROM python:3.9.1-slim

# create dir for holding test config json files
RUN mkdir /data

# copy python files
COPY config_helper.py config_helper.py
COPY test/config_helper_test.py config_helper_test.py
COPY test/data /data

# run db setup
CMD ["python", "config_helper_test.py"]
