# use python image
FROM python:3.9.1-slim

# set workdir
WORKDIR /home

# create dir for holding test config json files
RUN mkdir /data

# copy python files
COPY db_setup.py /home/db_setup.py

# run db setup
CMD ["python", "/home/db_setup_test.py"]
