# use python image
FROM python:3.9.1-slim

# set workdir
WORKDIR /home

# create dir for holding test config json files
RUN mkdir /data

# copy python files
COPY description_gen.py /home/description_gen.py
COPY test/description_gen_test.py /home/description_gen_test.py
#COPY test/data /data

# run db setup
CMD ["python", "description_gen_test.py"]
